general {
    ignore_empty_input = true
}

background {
    monitor =
    color = rgb(11, 12, 14)
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = rgb(17, 19, 24)
    outer_color = rgb(94, 196, 255)
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font
    font_color = rgb(215, 218, 224)

    placeholder_text = Enter Password
    check_color = rgb(94, 196, 255)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
