general {
    lock_cmd = bash ~/.config/artix-hypr-remix/bin/ahr-system-lock
    before_sleep_cmd = bash ~/.config/artix-hypr-remix/bin/ahr-system-lock
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

listener {
    timeout = 150
    on-timeout = pidof hyprlock || bash ~/.config/artix-hypr-remix/bin/ahr-system-lock
}

listener {
    timeout = 152
    on-timeout = bash ~/.config/artix-hypr-remix/bin/ahr-system-lock
    on-resume = hyprctl dispatch dpms on
}
